try {
  doesntExist;
} catch (error) {

} finally {
  console.log("test");
}